/** Class names owned by this plugin's stylesheet.
 *
 * Plain prefixed names rather than CSS Modules: a plugin served outside the
 * product's build has to compile and inject its own sheet, and a build-time
 * class map is machinery this package can do without.
 *
 * @module dsh-local-usage/client/classes
 */

/** Every class the panel's stylesheet defines. */
export const css = {
  calendar: 'dlu-calendar',
  calendarCaption: 'dlu-calendarCaption',
  calendarHeading: 'dlu-calendarHeading',
  calendarMeasure: 'dlu-calendarMeasure',
  calendarScroll: 'dlu-calendarScroll',
  calendarTitle: 'dlu-calendarTitle',
  calendarTotal: 'dlu-calendarTotal',
  calendarYear: 'dlu-calendarYear',
  cell: 'dlu-cell',
  cellRow: 'dlu-cellRow',
  cells: 'dlu-cells',
  controls: 'dlu-controls',
  dayDetail: 'dlu-dayDetail',
  dayHeader: 'dlu-dayHeader',
  dayTitle: 'dlu-dayTitle',
  dayTitleRow: 'dlu-dayTitleRow',
  dayWeekday: 'dlu-dayWeekday',
  disclosure: 'dlu-disclosure',
  disclosureBody: 'dlu-disclosureBody',
  disclosureSummary: 'dlu-disclosureSummary',
  empty: 'dlu-empty',
  facts: 'dlu-facts',
  failure: 'dlu-failure',
  gridRow: 'dlu-gridRow',
  header: 'dlu-header',
  headerText: 'dlu-headerText',
  heading: 'dlu-heading',
  hero: 'dlu-hero',
  heroDetail: 'dlu-heroDetail',
  heroLabel: 'dlu-heroLabel',
  heroValue: 'dlu-heroValue',
  legend: 'dlu-legend',
  legendHint: 'dlu-legendHint',
  legendLabel: 'dlu-legendLabel',
  legendPeak: 'dlu-legendPeak',
  legendScale: 'dlu-legendScale',
  legendSwatch: 'dlu-legendSwatch',
  monthLabel: 'dlu-monthLabel',
  monthRow: 'dlu-monthRow',
  notes: 'dlu-notes',
  numeric: 'dlu-numeric',
  panel: 'dlu-panel',
  priceCurrency: 'dlu-priceCurrency',
  priceMatch: 'dlu-priceMatch',
  priceTable: 'dlu-priceTable',
  pricingCaveat: 'dlu-pricingCaveat',
  pricingHint: 'dlu-pricingHint',
  pricingRatesLabel: 'dlu-pricingRatesLabel',
  projectBlock: 'dlu-projectBlock',
  projectCell: 'dlu-projectCell',
  projectHeading: 'dlu-projectHeading',
  projectName: 'dlu-projectName',
  projectPath: 'dlu-projectPath',
  projectTable: 'dlu-projectTable',
  range: 'dlu-range',
  ranges: 'dlu-ranges',
  scan: 'dlu-scan',
  status: 'dlu-status',
  subtitle: 'dlu-subtitle',
  summary: 'dlu-summary',
  tile: 'dlu-tile',
  tileDetail: 'dlu-tileDetail',
  tileLabel: 'dlu-tileLabel',
  tileValue: 'dlu-tileValue',
  tiles: 'dlu-tiles',
  tooltip: 'dlu-tooltip',
  tooltipDate: 'dlu-tooltipDate',
  tooltipDot: 'dlu-tooltipDot',
  tooltipEmpty: 'dlu-tooltipEmpty',
  tooltipHead: 'dlu-tooltipHead',
  tooltipHero: 'dlu-tooltipHero',
  tooltipHeroLabel: 'dlu-tooltipHeroLabel',
  tooltipHeroValue: 'dlu-tooltipHeroValue',
  tooltipRows: 'dlu-tooltipRows',
  tooltipWeekday: 'dlu-tooltipWeekday',
  warning: 'dlu-warning',
  weekday: 'dlu-weekday',
  weekdayColumn: 'dlu-weekdayColumn',
} as const
